### ISSUE TITLE
Team objects and multiple devices

### ISSUE THREAD

**Issue by julienmalard** [local-first-web/auth#6]
Many thanks for this library; it looks quite promising and I am very eager to try it out!

I had a few questions to which I could not find information in the documentation (apologies if it is there):

1. I can see example code for how a team object is created by the original creator. When one joins an existing team, however, how does one generate the team object from one's invitation key or proof of invitation? I imagine that this would be necessary in order to encrypt to the team or else, if permissions allow, add new members.
2. How can a user on one device add their other devices (keeping the same username)? Along the same lines, can one device revoke access to another if it is lost?
3. And finally, just to confirm: how would this work in the browser? Would different browsers on the same machine each be its own "device" with its own keys?

Many thanks,
Julien Malard

**Comment by HerbCaudill** [comment]
Hi, Julien! Thanks for checking this out and sorry for taking so long to respond. 

FWIW I wrote most of the docs before the codebase itself, and I haven't yet gone back and rewritten them to match the way things actually work; at this point they're probably misleading/incomplete/wrong. I probably need to make the "work in progress" notice on the main README a little stronger and louder: This project isn't really ready for anyone to use it yet. I *think* at this point I've settled most of the big design decisions, but any number of things may still be subject to change. 

Having said all that, some answers to your questions!

1. When you're joining with an invitation, you don't have a team object at first; you'd use the [`generateProof`](https://github.com/local-first-web/auth/blob/main/src/invitation/generateProof.ts) function to create a document that a team member can use to verify that you've received an invitation. Once they've validated your proof, it's their job to send you the current team chain and you can use that to create a Team object on your end. This whole process is encapsulated in the [`Connection`](https://github.com/local-first-web/auth/blob/main/src/connection/connection.ts) class. 

2. Adding devices works almost exactly like inviting new users, except that you're "inviting" yourself. You generate an invitation seed on your current device, and somehow get that seed over to the new device (maybe via a QR code, or just by typing it in). Then the device generates proof of invitation and shows that to the first team member they can find - most likely your current device, but could also be another team member altogether. [This test](https://github.com/local-first-web/auth/blob/main/src/team/invitations.test.ts/#L156-L190) walks through the process at a low level, and [this one](https://github.com/local-first-web/auth/blob/main/src/connection/connection.test.ts/#L485-L504) tells the same story at a higher level using the connection protocol. 

3. Yeah, different browsers would work like different devices, since there's no local storage that's shared across different browsers. 

Feel free to contact me via Twitter DM or email - contact info in my bio. I'm happy to answer any other questions, and/or schedule a time to talk - I'd be very interested to learn more about what you're working on and how this might be useful to you once it's released! Let me know. 

Herb
